repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        entry: cargo fmt --all --check
        language: system
        types: [rust]
        pass_filenames: false

      - id: clippy
        name: clippy
        entry: cargo clippy --workspace --all-targets -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-audit
        name: cargo-audit
        entry: cargo audit
        language: system
        pass_filenames: false

      - id: cargo-deny
        name: cargo-deny
        entry: cargo deny check
        language: system
        pass_filenames: false