/*
 * Help page component for the EzMemPass application.
 */

use leptos::prelude::*;

/// Help page component
#[component]
pub fn HelpPage() -> impl IntoView {
    view! {
        <div class="container">
            <h1>"Help & FAQ"</h1>
            <div class="card">
                <h2>"About EzMemPass"</h2>
                <p>
                    "EzMemPass is a tool that generates strong, memorable passwords using advanced language models and graph algorithms."
                </p>

                <h2>"FAQ"</h2>
                <div class="faq-item">
                    <h3>"How secure are the generated passwords?"</h3>
                    <p>
                        "The passwords generated by EzMemPass are designed to balance security and memorability. By default, they provide at least 60 bits of entropy, which is considered strong for most purposes."
                    </p>
                </div>
                <div class="faq-item">
                    <h3>"What does 'entropy' mean?"</h3>
                    <p>
                        "Entropy is a measure of password strength, expressed in bits. The higher the entropy, the more resistant the password is to brute-force attacks."
                    </p>
                </div>
                <div class="faq-item">
                    <h3>"Are my passwords stored anywhere?"</h3>
                    <p>
                        "No. EzMemPass generates passwords locally in your browser or device. No passwords are sent to or stored on any servers."
                    </p>
                </div>
                <div class="faq-item">
                    <h3>"What generation methods are available?"</h3>
                    <p>
                        "EzMemPass supports three generation methods: Language Model (most memorable), Graph Search (balanced), and Random (highest entropy)."
                    </p>
                </div>
            </div>
        </div>
    }
}
