[package]
name = "language_model"
version = "0.1.0"
authors = ["Asim Ihsan <asim.ihsan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
flate2 = "1.0.13"
unicode-normalization = "0.1.11"
serde_json = "1.0.44"
rand = "0.7.2"

crossbeam = "0.7.3"
scoped_threadpool = "0.1.9"
num_cpus = "1.11.1"