[build]
# Enables parallel compilation of crates in the workspace
jobs = 4

[target.aarch64-apple-darwin]
rustflags = [
  "--cfg",
  "erase_components",
]

[target.wasm32-wasip1]
rustflags = [
  "--cfg=web_sys_unstable_apis",
  "--cfg",
  "erase_components",
]

[target.wasm32-unknown-unknown]
rustflags = [
  "--cfg=web_sys_unstable_apis",
  "--cfg",
  "erase_components",
]
