[workspace]

members = [
    "lib/graph",
    "lib/integer_coding",
    "lib/passwordgen",
    "lib/passwordgenffi",
    "bin/ezmempass",
    "bin/language_model",
]

[profile.release]
lto = true
#codegen-units = 1
