[licenses]
unlicensed = "deny"
allow = [
    "Apache-2.0 OR MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "CC0-1.0",
    "MIT",
    "MPL-2.0",
]
copyleft = "warn"
default = "deny"

[bans]
multiple-versions = "warn"
wildcards = "deny"
deny = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[advisories]
vulnerability = "deny"
unmaintained = "warn"
notice = "warn"
ignore = []
