name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    steps:
      - uses: actions/checkout@v4

      - name: Setup mise and install tools
        uses: jdx/mise-action@v2
        with:
          version: "latest"
          install: true
          cache: true
          # log_level: warn # Optional: to make logs quieter

      - name: Cache cargo registry and target directory
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install additional cargo tools (via cargo-binstall managed by mise)
        run: |
          cargo binstall -y cargo-nextest cargo-deny cargo-audit cargo-llvm-cov cargo-udeps

      - name: Run CI checks (via Justfile)
        run: just ci

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Setup mise and install tools
        uses: jdx/mise-action@v2
        with:
          version: "latest"
          install: true
          cache: true

      - name: Cache cargo registry and target directory
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install cargo-llvm-cov and nextest
        run: cargo binstall -y cargo-llvm-cov cargo-nextest

      - name: Generate coverage report (via Justfile)
        run: just cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: lcov.info # This should match the output from `just cov`
          fail_ci_if_error: false
